# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtCreator/datasetWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1126, 579)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setMinimumSize(QtCore.QSize(300, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.txt_train_set = QtWidgets.QLineEdit(self.widget)
        self.txt_train_set.setObjectName("txt_train_set")
        self.verticalLayout_2.addWidget(self.txt_train_set)
        self.btn_train_set = QtWidgets.QPushButton(self.widget)
        self.btn_train_set.setObjectName("btn_train_set")
        self.verticalLayout_2.addWidget(self.btn_train_set)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.txt_test_set = QtWidgets.QLineEdit(self.widget)
        self.txt_test_set.setObjectName("txt_test_set")
        self.verticalLayout_2.addWidget(self.txt_test_set)
        self.btn_test_set = QtWidgets.QPushButton(self.widget)
        self.btn_test_set.setObjectName("btn_test_set")
        self.verticalLayout_2.addWidget(self.btn_test_set)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.txt_labels = QtWidgets.QLineEdit(self.widget)
        self.txt_labels.setObjectName("txt_labels")
        self.verticalLayout_2.addWidget(self.txt_labels)
        self.btn_labels = QtWidgets.QPushButton(self.widget)
        self.btn_labels.setObjectName("btn_labels")
        self.verticalLayout_2.addWidget(self.btn_labels)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.lst_numeric = QtWidgets.QListWidget(self.widget_3)
        self.lst_numeric.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lst_numeric.setAcceptDrops(True)
        self.lst_numeric.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lst_numeric.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lst_numeric.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lst_numeric.setDragEnabled(True)
        self.lst_numeric.setDragDropOverwriteMode(True)
        self.lst_numeric.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lst_numeric.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lst_numeric.setAlternatingRowColors(True)
        self.lst_numeric.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.lst_numeric.setMovement(QtWidgets.QListView.Free)
        self.lst_numeric.setProperty("isWrapping", True)
        self.lst_numeric.setWordWrap(True)
        self.lst_numeric.setObjectName("lst_numeric")
        self.verticalLayout_3.addWidget(self.lst_numeric)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_nominal = QtWidgets.QLabel(self.widget_4)
        self.lbl_nominal.setObjectName("lbl_nominal")
        self.verticalLayout_4.addWidget(self.lbl_nominal)
        self.lst_nominal = QtWidgets.QListWidget(self.widget_4)
        self.lst_nominal.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lst_nominal.setAcceptDrops(True)
        self.lst_nominal.setDragEnabled(True)
        self.lst_nominal.setDragDropOverwriteMode(True)
        self.lst_nominal.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lst_nominal.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lst_nominal.setAlternatingRowColors(True)
        self.lst_nominal.setMovement(QtWidgets.QListView.Free)
        self.lst_nominal.setProperty("isWrapping", True)
        self.lst_nominal.setWordWrap(True)
        self.lst_nominal.setObjectName("lst_nominal")
        self.verticalLayout_4.addWidget(self.lst_nominal)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_binary = QtWidgets.QLabel(self.widget_5)
        self.lbl_binary.setObjectName("lbl_binary")
        self.verticalLayout_5.addWidget(self.lbl_binary)
        self.lst_binary = QtWidgets.QListWidget(self.widget_5)
        self.lst_binary.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lst_binary.setAcceptDrops(True)
        self.lst_binary.setDragEnabled(True)
        self.lst_binary.setDragDropOverwriteMode(True)
        self.lst_binary.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lst_binary.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lst_binary.setAlternatingRowColors(True)
        self.lst_binary.setMovement(QtWidgets.QListView.Free)
        self.lst_binary.setProperty("isWrapping", True)
        self.lst_binary.setWordWrap(True)
        self.lst_binary.setObjectName("lst_binary")
        self.verticalLayout_5.addWidget(self.lst_binary)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.horizontalLayout.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.btn_train_set.clicked.connect(Dialog.btn_train_set_clicked)
        self.btn_test_set.clicked.connect(Dialog.btn_test_set_clicked)
        self.btn_labels.clicked.connect(Dialog.btn_labels_clicked)
        self.lst_numeric.customContextMenuRequested['QPoint'].connect(Dialog.show_right_click_context)
        self.lst_nominal.customContextMenuRequested['QPoint'].connect(Dialog.show_right_click_context)
        self.lst_binary.customContextMenuRequested['QPoint'].connect(Dialog.show_right_click_context)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Dataset"))
        self.label.setText(_translate("Dialog", "Training Set"))
        self.btn_train_set.setText(_translate("Dialog", "Select Training Set..."))
        self.label_2.setText(_translate("Dialog", "Testing Set ( Optional )"))
        self.btn_test_set.setText(_translate("Dialog", "Select Testing Set..."))
        self.label_3.setText(_translate("Dialog", "Column Labels"))
        self.btn_labels.setText(_translate("Dialog", "Select Column Labels..."))
        self.label_4.setText(_translate("Dialog", "Numerical Columns"))
        self.lst_numeric.setSortingEnabled(True)
        self.lbl_nominal.setText(_translate("Dialog", "Nominal Columns"))
        self.lst_nominal.setSortingEnabled(True)
        self.lbl_binary.setText(_translate("Dialog", "Binary Columns"))
        self.lst_binary.setSortingEnabled(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

